### ISSUE TITLE
Database 

### ISSUE THREAD

**Issue by Gurudevdatta** [SimCoderYoutube/UberClone#11]
Can you please upload the full DB schema (firebase)?

**Comment by Sithira** [comment]
it doesn't container schema @sangramkokate ... its NoSQL Database 😊

**Comment by sangramkokate** [comment]
@Sithira i know it is non sql Database but , we need to add the tables/fields in the database right? how can we guess what are the tables and the fields...after checking the login activity video shared i came to know about the users fields ..similarly i want to know for all the remaining app tables.
